jmueller17/Aixada

- manage_ufmember.php
- php/inc/memberuf.inc.php
...and hide `btn_reset_pwd` after a reset.
...and fix a html typo.
> Enlarge email field in manage_ufmember.php

- php/utilities/general.php
* send_mail(): Sends a email message as html UTF-8, reads "from" from config.php and sets a html wrap for the body content.
* get_list_query() and get_list_rs(): Retrieves a list as "item1,item2,..." from the database (eg list of a HU emails)
> Tools to simplify sending messages.

- manage_money.php
Ensure that the code `getGlobalBalances` is executed on return to the summary.
And ensure that each option is only in its section (Cash or C.Account)
> Ensure that the balance is updated on return to summary.

- php/inc/database.php
NOTE: The current code of dev3.0 also requires the patch #93 from 2.x.
Tested with incidents.
> dev3.0 DBWrap: Force SQL_MODE=''

- php/lib/deliver_email.php
NOTE: I've tried together with #114
> dev3.0 Use `basedir` from config.php to get URL of Aixada instead of code from 2.x

- modules/incidents/php/incidents_ctrl.php
- modules/incidents/php/incidents_mod.php
- php/lib/aixmodel.php
I tried emailing an incident but it seems that something went wrong in the dev3.0 code. 
This is the patch that I used.
> dev3.0 Fix code to run incidents/php/incidents_mod.php

- php/utilities/general.php
... and remove debug comments.
> Wrong url on message foot if Aixada is the root forlder.

- manage_orders.php
This is due to there is no attribute `row` in the previous `td`, so this expression `$(this).prev().attr('row')` not returns the id of product.
> "manage_orders.php": Review the first total fail to save.

- local_config/config.php.sample
- manage_orders.php
- php/ctrl/Orders.php
- php/ctrl/UserAndUf.php
- php/utilities/general.php
Features:
* Prices are used without revolutionary taxes (to can check provider note).
* The total order is dynamically calculated both with and without VAT (only one price shown if no VAT)
* The new price is stored in `unit_price_stamp` in the table `aixada_order_to_shop`
NOTES:
* Have been added literals and translated existing which were in English.
* To use literals in js, has prepared a `local_lang` as bridge object (so now the js code could be moved to a js file)
> manage_orders: Allow also check amounts and change prices reviewing orders. 

- css/aixada_main.css
Both align centered, with round corner and a slight background color (red or green)
And remove some excess of margin and padding on success messages.
> Make error messages have an appearance more coherent with success messages

- php/ctrl/ActivateRoles.php
See: http://php.net/manual/en/function.split.php
> Function split() has been DEPRECATED as of PHP 5.3.0

- js/aixadautilities/jquery.aixadaUtilities.js
To reproduce the problem e.g using `manage_money.php`:
* Select cashbox deposit option.
* Enter 1.00 as amount and "All other stuff" as type.
* Press button "Deposit!", then a red warning is showed, ok is expected.
* And **FAST** type some text as comment and already press the button "Deposit!"
* The success message is showed red instead of green! Opps!
> After a error if is fast corrected, then success is showed red.

- validate.php
**DANGER**: Try on `validate.php`:
* load a cart
* load another cart using `table#tbl_cart_listing`, oops! cart showed is combination of new cart and previous cart.
> Reset the previous cart when a new one is loaded.

- css/aixada_main.css
- local_config/config.php.sample
- local_config/custom_img/.gitignore
- login.php
- tpl/bill_model1.php
- tpl/incidents_model1.php
- tpl/order_model1.php
- tpl/report_header_writer.php
- tpl/report_order1.php
It been made some adjustments in the presentation of the reports.
See #141
> Allow customization just using config.php

- manage_orders.php
...and fix a typo: add space after `colspan="3"`
> Show UF name on review of orders.

- local_config/config.php.sample
- local_config/lang/ca-va.php
- local_config/lang/en.php
- local_config/lang/es.php
- validate.php
If validation is not performed the day that orders are distributed may be desirable to see all carts of the week.
> validate.php: Allows to show carts week.

- manage_orders.php
Currently when the page is refreshed the order detail information is displayed, and to view or revise an order the amounts of the previous order is displayed.
> manage_orders: Hide elements if not yet have good data loaded.

- .gitignore
- tpl/report_header_writer.php
Replace CIF/NIF with a smaller version & fix a bug with timeline.svg ignored file
> Improve CIF/NIF size on reports

- local_config/config.php.sample
- local_config/lang/ca-va.php
- local_config/lang/en.php
- local_config/lang/es.php
- manage_data.php
- php/ctrl/ManageData.php
- php/ctrl/ManageData/README.md
- php/ctrl/ManageData/aixada_account_desc.php
- php/ctrl/ManageData/aixada_iva_type.php
- php/ctrl/ManageData/aixada_payment_method.php
- php/ctrl/ManageData/aixada_rev_tax_type.php
- php/ctrl/ManageData/aixada_stock_movement_type.php
- php/ctrl/ManageData/aixada_unit_measure.php
- php/ctrl/ManageData/cistella_turn.php
- php/ctrl/ManageData_select.php
- php/inc/menu.inc.php
- php/lib/abstract_data_manager.php
Features:
* No longer use `canned_responses_XX.php` and `canned_queries.sql`
* Allows customization of the grid and the form.
* Is easy to add both verification client and server.
* The required code a very small for a new table.
New maintenance auxiliary tables are added, in particular for the revolutionary tax.
> Create manage_data.php to replace manage_table.php

- sql/dbUpgradeTo2.8.sql
And log each step executed on new table `aixada_version`.
> Check DB to run each step of dbUpgradeTo2.8.sql

- incidents.php
- index.php
- js/aixadacart/i18n/cart.locale-ca-va.js
- js/aixadacart/i18n/cart.locale-en.js
- js/aixadacart/i18n/cart.locale-es.js
- js/aixadacart/jquery.aixadacart.js
- js/aixadacart/jquery.aixadacart.mobile.js
- js/aixadautilities/jquery.aixadaUtilities.js
- js/aixadautilities/jquery.aixadaXML2HTML.js
- js/aixadautilities/loadPDF.js
- login.php
- manage_data.php
- manage_import.php
- manage_orderable_products.php
- manage_orders.php
- manage_preorders.php
- manage_providers.php
- manage_stock.php
- manage_table.php
- manage_ufmember.php
- report_sales.php
- report_shop_ufs.php
- shop_and_order.php
- torn.php
- validate.php
The code JavaScrip has been verified using Closure Compiler to show:
* undefined vars
* leaving commas
Syntax problems encountered by the compiler have been fixed.
> Fix JavaScrip syntax

- local_config/config.php.sample
- manage_orders.php
This UF is often used to take losses of the cooperative.
> Allows allocate losses order distribution to a UF

- manage_orders.php
- php/utilities/orders.php
NOTE: I remember that one cooperative mentioned that had problems with decimals on total quantities. This would serve to them.
Does anyone remember the name of this cooperative?
> Review orders: quantities are with 3 decimals in all cases.

- js/aixadacart/jquery.aixadacart.js
- shop_and_order.php
- validate.php
There are two small malfunctions in Cart:
* Auto-Save does not act in shop_and_order.php when changes quantity of a product in the right list.
* When quantity of a product is changed in the other left lists are not always updated.
> Adjusting update carts

- activate_all_roles.php
- activate_roles.php
- incidents.php
- index.php
- login.php
- manage_admin.php
- manage_data.php
- manage_import.php
- manage_money.php
- manage_mysettings.php
- manage_orderable_products.php
- manage_orders.php
- manage_preorders.php
- manage_providers.php
- manage_stock.php
- manage_ufmember.php
- report_account.php
- report_incidents.php
- report_sales.php
- report_shop_ufs.php
- report_stats.php
- report_stock.php
- report_torn.php
- shop_and_order.php
- torn.php
- tpl/bill_model1.php
- tpl/incidents_model1.php
- tpl/order_model1.php
- tpl/report_order1.php
- validate.php
See the latest comments in #156
> Force jQuery to not use cache.

- js/aixadacart/jquery.aixadacart.js
- manage_data.php
- manage_providers.php
- report_account.php
- report_stats.php
- report_torn.php
Note that the deleted lines (3 lines) on `manage_providers.php` cause a js errors and consequently controller error messages are not displayed.
> Fix js undeclared vars and other check using Closure Compiler.

- local_config/config.php.sample
- php/lib/import_dates4products.php
Field `iva_percent_type_id` does not exit in database, right name is `iva_percent_id`
> Fix mismatch to import VAT.

- manage_orderable_products.php
When a provider has a lot of products (eg over 560) when provider is selected it may cause the browser detects excessive time execution and ask *"A script on this page may be busy... continue?"*
Patch proposed optimizes the code and fixes a case where `$('.loadSpinner')` is not displayed when the browser is working.
Note:The main improvement is due to usage of new array `gdatesIsPast[]` that stores if a date is in the past or not.
> manage_orderable_products: long time to activate many products

- local_config/lang/ca-va.php
- local_config/lang/en.php
- local_config/lang/es.php
- manage_money.php
- php/ctrl/Account.php
- php/lib/account_operations.php
Show provider balances, similar as HU balances.
(only when config value: `$accounts['use_providers']` is true)
> manage_money: Show provider balances

- manage_orderable_products.php
Sorry my PR #193 causes a js error on `manage_orderable_products.php` and cumulative orders are not shown.
> Fix bug introduced by #193

- sql/aixada.sql
- sql/dbUpgradeTo2.8.sql
Up to 127 units are many, but not sufficient for somebody.
> Change unit id from tinyint to smallint

- CHANGELOG-es.md
- local_config/lang/ca-va.php
- local_config/lang/en.php
- local_config/lang/es.php
- manage_orders.php
- php/ctrl/Orders.php
- php/utilities/orders.php
Reviewing orders allows adding quantities of any product of the provider and HU. Only nedded ara active.
New button "* Add item *"
Now *order=editTotalQuantity* works if the existing total is zero, in this case the new total is evenly distributed among the HUs on the order.
Reviewing a new button "*Add item*" appears,
It is only necessary that the products and HUs are active. But it is not necessary that the product is activated for the date of the order, after add it the product is activated for the date.
> Allows adding product or HU on reviewing orders.

- sql/aixada.sql
> Missing a comma

- manage_orders.php
- manage_providers.php
* manage_providers.php: On a provider has been noted that may not load drop-downs VAT and Imp.Rev.
* manage_orders.php: Changed preventively.
Related PR: #215
> Use ajaxQueue in two more requests (see #215)

- php/inc/header.inc.base.php
- tpl/bill_model1.php
- tpl/incidents_model1.php
- tpl/order_model1.php
- tpl/report_order1.php
> Use aixada_js_src() on reports to fix bug

- js/aixadacart/jquery.aixadacart.js
- shop_and_order.php
Currently is possible to write in notes when order is closed  
(it's not serious since the controller ignores this changes)
This patch prevents write in note when a order is closed.
> Prevents write in note if the order is closed

- php/ctrl/InstallAixada.php
> Verify if it can be updated automatically.

- install.php
- php/ctrl/InstallAixada.php
* Fix a error using PHP5.3
* Show mode: new install or update.
* In mode update show warnings before "Do install":
* Must identify as a user.
* Only a user with role "Hacker Commission" can do it.
* Aixada is previous to 2.7
> Install: Fix error using PHP53 and show mode.

- install.php
- php/ctrl/InstallAixada.php
Used in #251 to see sql session variables.
> install.php: Allow get sql information to check possible problems

- php/utilities/general.php
Fix bug introduced by me in #214, sorry
Commented in [#258](https://github.com/jmueller17/Aixada/issues/258#issuecomment-480601513)
> BUG: Using mail() of PHP cc anb bcc are ignored

- install.php
- php/ctrl/InstallAixada.php
It worked but the presentation was a bit chaotic
> Make `install.php` easier to read

- php/lib/account_operations.php
[Comment on issue #288](https://github.com/jmueller17/Aixada/issues/288#issuecomment-1032980699)
> Fix default value as array

- php/utilities/orders.php
El error reportado en #308 aparece con Mysql 8.0 pero no con Mysql 5.7 (el que yo tenia para desarrollo)
NOTA: Este error lo introduje yo en el PR #305
> Fix Issue 308 produced by PR 305

- ajuda.php
- js/aixadautilities/jquery.aixadaMenu.js
- local_config/config.php.sample
- local_config/lang/ca-va.php
- local_config/lang/es.php
- manage_calendar.php
- php/ctrl/Calendar.php
- php/inc/menu.inc.php
- php/lib/calendar_operations.php
- sql/aixada.sql
Faig una proposta que fem servir a la nostra cope per incorporar la gestió de torns i canviar el format de l'ajuda per fer-lo més accessible.
> Proposta de calendari de torns i nou format Ajuda

- php/inc/database.php
- sql/queries/aixada_queries_account.sql
- sql/queries/aixada_queries_cart.sql
- sql/queries/aixada_queries_dates.sql
- sql/queries/aixada_queries_incidents.sql
- sql/queries/aixada_queries_order.sql
- sql/queries/aixada_queries_products.sql
- sql/queries/aixada_queries_providers.sql
- sql/queries/aixada_queries_report.sql
- sql/queries/aixada_queries_shop.sql
- sql/queries/aixada_queries_statistics.sql
- sql/queries/aixada_queries_useruf.sql
- sql/queries/aixada_queries_validate.sql
- sql/setup/aixada_queries_all.sql
See comments on issue #319 of @Jorgepastorr
> Ensure that procedures are executed in the proper SQL_MODE
