jmueller17/Aixada

local_config/lang/ca-va.php, local_config/lang/en.php, local_config/lang/es.php
* en & es: remove duplicate `ordered_for`
* es & ca-va: remove duplicates `ti_mng_stock`
* ca-va: **add** `msg_err_productshort` !!!!
For this work have made changes to the sources ca-va.php & es.php to match the structure to the code of en.php: the position of some keys of `es` has changed and and added/removed newlines and comments on both.
=> Go over keys of the three languages.

php/lib/deliver_email.php
Patch to `dev3.0` from ``master` #111
=> dev3.0: Wrong url on message foot if Aixada is the root forlder.

manage_money.php
Buttons `deposit` & `withdrawal` fail (no movements are stored in the accounts) and `set_balance` works ok using FF-35
Using Chrome-40 the movements are stored in the accounts but not reported success to the user.
Patch tested using: FF-35, Chrome-40 & IE
=> manage_money.php: Buttons fail using Firefox

sql/queries/aixada_queries_order.sql, sql/setup/aixada_queries_all.sql
Reviewing an provider order when distributed the data stored in `iva_percent` and `rev_tax_percent` of table `aixada_shop_item` are the id instead of percentages.
After validating families the data in `iva_percent` and `rev_tax_percent` of table `aixada_shop_item` are properly stored as percentages.
=> "id" instead "percentage" reviewing an provider order.

js/aixadacart/jquery.aixadacart.js
Total VAT must be with rev_tax applied:
Otherwise when rev_tax and IVA are not zero `total` is not equal to `total_net + rev_tax_total + iva_tax_total`
=> Total VAT must be with rev_tax applied, otherwise total

sql/dbUpgradeTo2.8.sql
Otherwise some queries returns a empty set as for example the revision value at see a provider order.
=> Fill table aixada_order_to_shop at migration to 2.8 version

php/ctrl/TableManager.php
On creation of table `aixada_price` is declared
`foreign key (operator_id) references aixada_user(id)`
but value inserted is `$_SESSION['userdata']['uf_id']`.
=> Wrong value insert on aixada_price.operator_id by TableManager.php.

local_config/lang/ca-va.php, local_config/lang/en.php, local_config/lang/es.php, manage_orders.php, php/ctrl/Orders.php, php/utilities/orders.php
Only could add products that are already been ordered by another UF.
NOTES:
* Changed the code of the cell, children `<p>` is removed, now the quantity ordered is put into the `<td>`.
* The parameter `product_uf` on `oper=editQuantity` has changed to 2 more logical parameters: `product_id` and `uf_id`.
* Have moved language texts from `manage_orders.php` to respective language files (refactor branch `a-edit_order_prices`)
* The executable code has moved from `ctrl/Orders.php` to new functions on `utilities/orders.php` (refactor branch `a-edit_order_prices`)
=> Allow add products when reviewing an order.

css/aixada_main.css
This change allow to use classes `textAlignRight` & `textAlignCenter` on `<th>` and `<td>` elements without a sub-element as `<p>`.
So allows for a less overhead html code.
This affects some existing presentations that had not been taken into account that alignment was forced to the left on `table.tblListingDefault th/td`. Especially in some titles e.g. "*Balace*" on `validate.php`
=> Able to use align on th/td on table.tblListingDefault

php/utilities/general.php
Causes errors writing code when calling `get_param_int('no_parameter', '24')` returns null. So if the default value is a string that represents a number is accepted and converted to numeric.
=> get_param_int: As default allow a string that represents a number

php/utilities/useruf.php
Using UTF-8 (with BOM) can cause loss of the last 3 characters in the ajax XML requests, (or additional 3 (3 + 3 = 6) as described in PR #134)
Yet BOM seems that is not the only reason, in my tests it is clear that this is one of the reasons.
Justification note: In my current development server on `UserAndUf.php?oper=getMemberListing&all=1` only lose 3 chararters but on my old server (it broke) 6 characters were lost using this control and the others controls 3 characters were lost. Currently this is the only control who fails me. And removing BOM everything works.
=> Use the UTF-8 without BOM.

css/aixada_main.css
The style `ui-lightness` shows errors blank. After #138, to have a good contrasts suggested changing the color (to give a good contrasts in relation to the `background-color:#fdd`)
=> ui-state-error: Ensure contrasts in all styles

php/utilities/general.php
Using PHP on Apache2 if a XML response is longer that 8000 chars 3 or 6 last chars are cut. This is produced on printXML method of `utilities/general.php`.
Seems that the problem is due to this PHP bug:
https://bugs.php.net/bug.php?id=45945
Also comented on:
http://stackoverflow.com/questions/22121282/php-inserts-hex-number-of
NOTE: Unfortunately I was unable to determine whether possible to lose more characters, but those tests
I made this patch allows working with Aixada without this problem.
=> The XML can be cut in the last three characters.

php/lib/abstract_data_manager.php
SORRY!!!
I was using a server PHP 5.5 and did not see me he had used incompatible syntax with PHP 5.3.
I searched exhaustively around the source Aixada and I've only detected this point.
NOTE Now I'm already using 5.3
NOTE2: Bug was also before yesterday in #142, but yesterday is fixed
Apologies!!
=> Fix BUG using PHP 5.3

local_config/config.php.sample, manage_admin.php, php/ctrl/Admin.php
By default the current script method is used and whether its execution fails due to host restrictions internal method is used.
To force usage of internal method could set `public $db_backup_method = 'int';`
(For data migration internal method provides a more comfortable to read or edit db-backup sql files)
=> Provides a internal bd backup method using only mysqli

css/aixada_main.css, local_config/lang/ca-va.php, local_config/lang/en.php, local_config/lang/es.php, manage_orders.php, php/ctrl/Orders.php, php/utilities/orders.php
Additionally:
* It has translated the texts found only in English.
* The dates appear translated.
* The usage of configuration parameter `$development` and `$_SESSION['dev']` is removed from `manage_orders.php`, because for years is outdated in the `make` code to minimize js (many pages have no generated the corresponding `js_for_%.min.js`, so this is cause for comment on another issue)
* The dialog buttons are inhibited when the dialog is used to then display the status of a ajax response.
* Prevents there are no empty carts after erasing the distribution.
=> Allow to review an order distributed without losing the previous review done.

sql/queries/aixada_queries_order.sql
If at review an order some product are checked as not arrived (but without changing any quantity) when distribution is made the status is set as "revised unchanged", oops!
=> Review orders: At distribution not always status assigned is correct.

sql/queries/aixada_queries_order.sql
If is started a review of the order and order is reopen then aixada_order is not deleted (due to constrains integrity) and there are also zomby records on "aixada_order_to_shop" with the order_id reopened.
=> When reopens an order, must delete "aixada_order_to_shop".

local_config/config.php.sample, local_config/lang/ca-va.php, local_config/lang/en.php, local_config/lang/es.php, manage_orders.php, php/ctrl/Orders.php, php/lib/account_operations.php, php/lib/validation_cart_manager.php, php/utilities/orders.php, sql/queries/aixada_queries_validate.sql
For some cooperatives (ours, Travalera and Guixa -which is studying launch Aixada--) the verification products from orders in a second step after the distribution is not necessary.
The proposal adds this feature, is configurable and is disabled by default.
=> Proposal: Allows configure to directly distribute and validate orders.

php/utilities/orders.php
NOTE: `account_operations->add_operation` check if amount has only 2 decimals, otherwise trow a error.
=> Bug on validate directly: Ensure two decimals on provider account.

local_config/lang/ca-va.php, local_config/lang/en.php, local_config/lang/es.php, manage_orders.php
But it allows reopen orders only until the date of delivery (included). Otherwise it is useless since last date of delivery orders can not be changed.
Also fix a small mismatch presentation that showed how `Closed` a order to close today, now as "Closes in days" shows `0` instead of `Closed`.
=> Make more explicit the UI of reopen order

local_config/config.php.sample
After adding into configuration the `$order_distribution_method` this is the option that keeps the previous operation.
=> Fix inaccuracy: By default use configuration 'only_distribute'

js/aixadacart/jquery.aixadacart.js, local_config/config.php.sample, local_config/lang/ca-va.php, local_config/lang/en.php, local_config/lang/es.php, php/ctrl/Validate.php, php/utilities/shop_and_order.php, validate.php
Allows create a empty cart at validation. This is usefully to assign products to a UF with no orders and no shop or when is used the option `$order_distribution_method = 'distribute_and_validate'`.
If the config `validate_btn_create_carts` is true a button "Create cart" is displayed when is select a UF without  unvalidated carts.
NOTE: It also fixes the problem to add some products into an empty cart.
=> validation.php: Allows create a empty cart at validation

local_config/config.php.sample
Used by: `php\inc\authentication.inc.php`  and `php\utilities\useruf.php`
The option `$development` is off by #186, sorry!
=> Option $development is still used.

php/utilities/general.php
With this extra space, the malformed Cc or Bcc header was considered as the
first line of the body of the email, a new line was inserted before it. This
new line was preventing the following headers (including Content-Type) to be
interpreted as headers and the HTML email was displayed in plain text.
(text by ricola)
Reported by Josu in [Aixada-Dev](https://lists.riseup.net/www/info/aixada-dev) and tested by ricola.
Please merge, thanks.
=> [PATCH] Remove extra space in email headers

index.php, sql/queries/aixada_queries_dates.sql, sql/setup/aixada_queries_all.sql
Fix a small mismatch presentation on `index.php` that showed as `Closed` a order to close today. After this patch shows 0 as days to close instead of *"order is closed"*. Also show order to close today in *"Upcoming orders"* tab. (see similar issue on #176)
=> Fix small mismatch presentation of not closed a order in index.php.

local_config/lang/ca-va.php, local_config/lang/en.php, local_config/lang/es.php, php/lib/order_cart_manager.php, shop_and_order.php
"shop_and_order.php" allows add products when no exist a open date for order.
As to reproduce:
* Begin an order.
* Close the order in another browser.
* Add a product, oops! tells us that it has been successfully saved!!
* but luckily!, the product is not added.
* a new open order exist but we can't even see or close.
* If we modify existing quantities also tells us that it has been successfully saved!!
* but luckily!, not is true!
This patch aims to prevent add products when closed date. And also notify to the user that their data has not been saved.
=> On new order should check if order is already closed.

sql/queries/aixada_queries_products.sql, sql/setup/aixada_queries_all.sql
Current sql procedure `get_preorderable_products` returns two columns `unit_price` and the last column is without VAT and Rev.Tax. This erroneous column is used by `shop_and_order.php`.
=> Cumulative order: fix to uses final price.

php/ctrl/Orders.php, php/utilities/orders.php, sql/queries/aixada_queries_products.sql, sql/setup/aixada_queries_all.sql
`manage_orders.php` allows close an order if it is open when the list orders is displayed. But what happens if another user has closed the order after displaying the list? Yes... the order will be closed twice, and activating provider products fail!
This patch proposes some controls on the server to prevent actions on orders that no longer have the state shown in the list or in the distribute page.
=> The controller should check the order status.

local_config/lang/ca-va.php, local_config/lang/en.php, local_config/lang/es.php, php/utilities/orders.php
The empty carts are reused for the same date, and also warns and cancel if there are pending validate products carts.
=> The empty carts can cause errors to distribute and validate.

php/lib/order_cart_manager.php
Remove `true ||` forgotten that I used to force to show error messages on development.
Sorry :-(
=> Fix bug introduced by #205

CHANGELOG-es.md, local_config/config.php.sample, php/utilities/general.php
Aixada puts in 'reply-to' the 'to' or 'cc' of mails, but some hosting
filters interpret this as a possible malicious attempt to send SPAM.
New configuration parameter 'email_safe_replyTo' is suggested, and it is recommended to set them to true.
Comment by a hosting technical support:
"Usually spammers use this technique to send spam. You should
avoid using freemail service provider addresses
in header 'from' or 'reply-to' address."
=>  Prevent false locks as SPAM when sending mails.

manage_providers.php
Correctly put the 'default' value in two drop-down lists when displaying the new provider option.
=> Set 'default' as value when creating provider.

php/inc/memberuf.inc.php, sql/aixada.sql
It is proposed to force SQL_MODE in creation tables to avoid errors.
Also is proposed:
* allow null in `last_login_attempt` and `last_successful_login` of `aixada_user`.
* show `last_login_attempt` instead of `last_successful_login` since only `last_login_attempt` is updated.
=> Depending on the SQL_MODE the installation may fail.

css/aixada_main.css, manage_orderable_products.php
The problem was that sometimes the emergent menus disappeared when activated, this was due to the cell size change produced by the 'mouseleave' event.
A color frame of 1px is proposed. It uses the background color and changes color on hover. It also prevents going the font from bold to normal. In this way the cells not change their size on hover.
=> Activate products: maintain the width and height of the cells on hover

CHANGELOG-es.md, local_config/config.php.sample, php/ctrl/ShopAndOrder.php, php/inc/menu.inc.php, php/utilities/shop_and_order.php
This proposal expands the configuration possibilities for direct store.
Possible config values:
- 'order_and_stock': The shop is shown with all active products
(default if is missing or true)
- 'only_stock':      The shop is shown only with active stock products.
- false:             The shop is not shown.
When uses 'only_stock' also the list of providers and the categories are reduced to cases where have active stock products.
See issue  #231
=> Shop only with stock products

CHANGELOG-es.md, CHANGELOG.md, php/ctrl/InstallAixada.php
Al intentar documentar los últimos cambios me ha parecido más lógico separar los cambios por años (para poder hablar de un CHANGELOG), y así he procedido.
Luego he puesto los nuevos cambios del 2018.
También he suprimido la referencia a versiones ya que hace tiempo `master` es la fuente correcta para instalar Aixada.
También he actualizado la wiki referente al uso de `install.php`.
Trabajando en la wiki he visto alguna pagina que se podian borrar:
* [Coopide](https://github.com/jmueller17/Aixada/wiki/Coopide)
* [Menu-Eco](https://github.com/jmueller17/Aixada/wiki/Menu-Eco)
* [New-App-Day](https://github.com/jmueller17/Aixada/wiki/New-App-Day)
**¿Hay problema en borrarlas?**
También se podría borrar:
* `sql/dbUpgradeTo2.1.sql`
* `php/ctrl/Install.php` (no se usa en ningún *.js, *.php ni …
=> CHANGELOG-es: Añadir cambios 2018 y agrupar por años

php/inc/database.php
After spending a lot of time, I happened to have the error reported in #228 in my test server, and this has allowed me to find the solution.
=> Fix error MySQL error Data too long in GROUP_CONCAT()

php/external/jquery-fileupload/.gitignore, php/external/jquery-fileupload/Dockerfile, php/external/jquery-fileupload/README.md, php/external/jquery-fileupload/UploadHandler.php, php/external/jquery-fileupload/docker-compose.yml, php/external/jquery-fileupload/files/.gitignore, php/external/jquery-fileupload/files/.htaccess, php/external/jquery-fileupload/index.php, php/external/spreadsheet-reader/.gitignore, php/external/spreadsheet-reader/CHANGELOG.md, php/external/spreadsheet-reader/LICENSE.md, php/external/spreadsheet-reader/README.md, php/external/spreadsheet-reader/SpreadsheetReader.php, php/external/spreadsheet-reader/SpreadsheetReader_CSV.php, php/external/spreadsheet-reader/SpreadsheetReader_ODS.php, php/external/spreadsheet-reader/SpreadsheetReader_XLS.php, php/external/spreadsheet-reader/SpreadsheetReader_XLSX.php, php/external/spreadsheet-reader/_FORKS.txt, php/external/spreadsheet-reader/composer.json, php/external/spreadsheet-reader/php-excel-reader/excel_reader2.php, php/external/spreadsheet-reader/test.php, php/lib/abstract_import_manager.php, php/lib/data_table.php
This fix problems of import/export Excel with PHP7.x (tested on 7.3)  
It also required some small adjustment in the code of Aixada 872d4bfc507415fe18f9ae244f79d69af37ecbf4.
NOTE: [spreadsheet-reader](https://github.com/nuovo/spreadsheet-reader) seems abandoned and is not compatible with PHP7. Is used a fork of @fujaru + [PR#3](https://github.com/fujaru/spreadsheet-reader/pull/3) for PHP7.3
NOTE-2: This code has already been in production for two weeks.
=> Most modern version of spreadsheet-reader

php/inc/authentication.inc.php
This causes that the theme requested is `''` and `css\ui-themes\\jqueryui.css` file is not found.
It is proposed to force `'start'` theme when there is no established theme.
=> After install Aixada no theme is set for Admin.

install.php, php/ctrl/Admin.php, php/ctrl/InstallAixada.php
The backup and database update may require more time.
It is proposed to extend the time.
And in database update also is proposed write each step in the log file instead of at the end. So if process is interrupted can see in what step of the execution happened.
There are also cosmetic changes on the petition page `install.php`
=> Allow more time in bd processes

local_config/config.php.sample, php/inc/adminDatabase.php, php/inc/database.php
It is proposed to allow configure `$db_host` using the syntax `$db_host='myHost:9999'` to indicate a different port from the default.
This is useful when developing, allows use different bd systems on the same host, each one in different ports.
NOTE: `$db_type` is removed from `config.php.sample` since it is not used.
=> Allow to connect mySql to a different port.

php/lib/order_cart_manager.php
The error was introduced by me in #239
Since there are no longer two tabs on the shopping cart, one for the date and another for the cumulative ones, there is no more double information in oper=commit of the order of the date and the preoder=true. Currently cumulatives are also worked as of date.
I did not see this `or date_for_order='1234-01-23'` in this `DELETE`, I'm sorry.
=> BUG: Cumulative order of the UF is lost if after making a normal order.

php/inc/database.php
The use of `SQL_MODE = ''` is essential for the use of dates in various procedures.
MariaDB 10.3.13 ignores statement `SET SESSION SQL_MODE = '';`, which has caused problems in different installations.
See: #251
=> Fix problem that does not change SQL_MODE = '' using MariaDB 10.3.13

Dockerfile, docker-compose.yml
- Fix some errors on docker, caused by `mysqli` missing.
- Move `Dockerfile` to the root level, for visibilty
- Add `docker-compose` file with `mariadb` and `phpmyadmin` for a completely dockerized local environment.
Fixes #267
=> Fix dockerfile and improve local environment

php/inc/database.php, php/lib/account_operations.php, php/lib/import_products.php, php/utilities/general.php, php/utilities/useruf.php
**Fix FATAL ERROR introduced in PR #289**
* Fix some deprecate syntax in PHP-8
Remaining problems in \php\external
* swiftmailer-5.x (syntax $char{} )
* ZendGdata-1.12.2 (seems like quite a few problems)
* spreadsheet-reader (seems like quite a few problems)
Using PHP-8 (and it is thought that also PHP 7.4)
* import/export does not work
* sending messages not tested yet, it is thought that it will not work
=> Php8 initial

php/lib/import_products.php
Using an import template with `'deactivate_products' => true` products with reference field as null are not deactivated.
=> BUG: using import with `deactivate_products=true`

Dockerfile, docker-compose.yml
Relacionat amb l'issue  [#299](https://github.com/jmueller17/Aixada/issues/299).
1. He augmentat la versió de php a la imàtge de Docker, de 7 a 8.1
2. He fet descansar la instal·lació de les extensions de php sobre els _helper scripts_ que la propia imàtge de docker oficial de php recomana utilitzar al seu [README](https://hub.docker.com/_/php/)
3. He fet alguns canvis a la configuració de l'arxiu `docker-compose.yml`
=> Docker fixes and upgrade

php/utilities/incidents.php
Bones,
Al crear un nou incident per defecte s'envia a tots els usuaris de la cooperativa, estiguin actius o no. 
$rs = do_stored_query('get_member_listing', 1);
per
$rs = do_stored_query('get_member_listing', 0);
Perquè la rutina que crea la llista d'usuaris get_members_listing si rep un valor 1 inclou els usuaris inactius.
=> Modificar enviament incidents

js/aixadacart/jquery.aixadacart.js, php/lib/validation_cart_manager.php, php/utilities/orders.php
Fix issue #303
If a cart is empty it is not possible to validate, it remains in the UF and there is no way to remove.
It is proposed to activate the validation process, in fact `validation_cart_manager` suppresses a empty cart. Also in the other validation way `direct validate order()` of `utilities/orders.php` remove empty carts of date for shop. And on validation screen `validate.php`, now validate button is enabled for empty carts.
=> Fix issue #303 to validate empty carts

php/lib/shop_cart_manager.php
Corrige el error SQL al validar carritos que provienen de un pedido al que se le han agregado productos después de distribuir.
=> Fix issue #309

css/aixada_main.css
Implements sticky table headers css pattern from [css-tricks](https://css-tricks.com/position-sticky-and-table-headers/).
Sticky table headers allow to maintain columns context on tables with more rows than the screen viewport can show.
=> Sticky table headers

ajuda.php, manage_calendar.php, php/ctrl/Calendar.php, php/lib/calendar_operations.php
Bug fixes in the upgrade `aixada_torns` (by PR #306)
PHP warnings fided:
- Notice: Constant DS already defined in `\ajuda.php` on line 3
- Notice: Constant __ROOT__ already defined in `\ajuda.php` on line 4
- Warning: count(): Parameter must be an array or an object that implements Countable in `\php\lib\calendar_operations.php` on line 126
- Notice: Undefined variable: mateixTorn in `\php\lib\calendar_operations.php` on line 63
Uso de sintaxis no segura de `<?` en `manage_calendar.php` (algunas versiones de PHP ya no ejecutan la sentencia)
Especificar siempre el valor por defecto al usar get_config() si no se gestiona `null` como resultado
=> Bug fixes in the upgrade Aixada_torns (by PR #306)

sql/dbUpgradeTo2.8.sql
Contemplar la nueva tabla `aixada_torns` (creada por el PR #306 de @mamuts)
en el `dbUpgradeTo2.8.sql` para que se cree si no existe.
Esto también hará que `/install.php` añada la tabla.
=> Añadir nueva tabla `aixada_torns` en la actualización.

php/inc/adminDatabase.php
Los dos puntos en el nombre causaba que la copia no se almacenara en el servidor, aunque sí se podía descargar en `/manage_admin.php`
=> Remove ":" from the backup name and add seconds
